### ISSUE TITLE
use with expo-camera

### ISSUE THREAD

**Issue by billtlee** [reime005/react-native-camera-hooks#4]
Hi,

Is it possible to use this with expo-camera rather than react-native-camera?

Thanks,

Bill

**Comment by reime005** [comment]
I'm working on that. Will be possible soon

**Comment by reime005** [comment]
@billtlee you may try the beta: `yarn add react-native-camera-hooks@beta`. any feedback is appreciated

**Comment by FinnFrotscher** [comment]
is it live?

**Comment by jgall** [comment]
Hi folks, any idea if progress has been made on this front? 

Thanks :)

**Comment by reime005** [comment]
support for expo should already be active for months. I've also added an example expo app. Let me know how/if this works @FinnFrotscher @jgall

**Comment by FinnFrotscher** [comment]
will check [example](https://github.com/reime005/react-native-camera-hooks/blob/master/example/ExpoExample/App.tsx)
